apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-auth-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Id-Token, Authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "12k"
spec:
  ingressClassName: nginx
  rules:
  - host: proxy-server.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-manager-service
            port:
              number: 4180